language: php
php:
  - 5.6
script:
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash
  - composer install
  - phpunit
  - phpcs --standard=PSR2 src/
  - phpcs --standard=PSR2 tests/
  - bin/atoum --test-all
