language: php
php:
  - 5.6
before_script:
  - phpenv rehash
  - composer install
script:
  - phpunit
  - phpcs --standard=PSR2 src/
  - phpcs --standard=PSR2 tests/
after_script:
  - php vendor/bin/coveralls -v
